# Generated by Django 5.2 on 2025-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard', 'Can view the global dashboard'), ('export_reports', 'Can export attendance reports'), ('approve_leaves', 'Can approve employee leaves')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
