# Generated by Django 5.2 on 2025-05-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_admin_dashboard', 'Can view the admin dashboard')]},
        ),
    ]
