# Generated by Django 5.2 on 2025-05-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_globalpermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_admin_dashboard', 'View the admin dashboard'), ('view_emp_dashboard', 'View the employee dashboard'), ('view_hod_dashboard', 'View the head of department dashboard'), ('view_employee_list', 'View the employee list'), ('view_employee_archive_list', 'View the archive employee list'), ('view_department_list', 'View the department list'), ('view_shift_list', 'View the shift list'), ('view_daily_attendance', 'View the daily attendance'), ('view_monthly_attendance', 'View the monthly attendance'), ('view_attendance_report', 'View the attendance report'), ('view_public_holiday_list', 'View the public holiday list'), ('view_employee_leave_list', 'View the employee leave list'), ('view_daily_leave_list', 'View the daily leave list'), ('view_device_list', 'View the device list'), ('view_user_list', 'View the users list'), ('view_roles_list', 'View the roles list'), ('view_activity_log_list', 'View the activity logs'), ('view_backup', 'View the backup option')]},
        ),
    ]
