# Generated by Django 5.2 on 2025-05-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_globalpermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_admin_dashboard', 'View the admin dashboard'), ('view_employee_dashboard', 'View the employee dashboard'), ('view_hod_dashboard', 'View the head of department dashboard'), ('view_employee_list', 'View the employee list'), ('add_employee', 'Add employee'), ('change_employee', 'Change employee'), ('delete_employee', 'Delete employee'), ('view_employee_profile', 'View employee profile'), ('view_employee_documents', 'View employee documents'), ('add_employee_documents', 'Add employee documents'), ('delete_employee_documents', 'Delete employee documents'), ('change_employee_password', 'Change employee password'), ('view_employee_biometric', 'View employee biometric data'), ('change_employee_biometric', 'Change employee biometric data'), ('view_employee_settings', 'View employee settings'), ('view_employee_archive_list', 'View the archive employee list'), ('delete_employee_archive', 'Delete the archive employee'), ('view_department_list', 'View the department list'), ('add_department', 'Add the department'), ('change_department', 'Change the department'), ('delete_department', 'Delete the department'), ('view_shift_list', 'View the shift list'), ('add_shift', 'Add the shift'), ('change_shift', 'Change the shift'), ('delete_shift', 'Delete the shift'), ('view_daily_attendance', 'View the daily attendance'), ('view_daily_report_all_employee_by_hod', 'View department-based employee list by the head of department in daily attendance'), ('view_monthly_attendance', 'View the monthly attendance'), ('view_attendance_report', 'View the attendance report'), ('view_public_holiday_list', 'View the public holiday list'), ('add_public_holiday', 'Add the public holiday'), ('delete_public_holiday', 'Delete the public holiday'), ('view_employee_leave_list', 'View the employee leave list'), ('view_employee_leave_details', 'View the employee leave details'), ('confirm_employee_leave', 'Confirm the employee leave'), ('add_employee_leave', 'Add the employee leave'), ('delete_employee_leave', 'Delete the employee leave'), ('view_daily_leave_list', 'View the daily leave list'), ('view_daily_leave_details', 'View the daily leave details'), ('confirm_daily_leave', 'Confirm the daily leave'), ('add_daily_leave', 'Add the daily leave'), ('delete_daily_leave', 'Delete the daily leave'), ('view_device_list', 'View the device list'), ('add_device', 'Add device'), ('change_device', 'Change device'), ('delete_device', 'Delete device'), ('view_user_list', 'View the users list'), ('add_user', 'Add user'), ('change_user', 'Change user'), ('delete_user', 'Delete user'), ('view_roles_list', 'View the roles list'), ('add_role', 'Add role'), ('change_role', 'Change role'), ('delete_role', 'Delete role'), ('view_activity_log_list', 'View the activity logs'), ('view_backup', 'View the backup option')]},
        ),
    ]
