# Generated by Django 5.2 on 2025-04-23 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Department Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Custom ID to print on badges/cards', max_length=50, unique=True, verbose_name='Employee ID')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='Father’s Name')),
                ('grand_father_name', models.CharField(blank=True, max_length=100, verbose_name='Grandfather’s Name')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Position/Title')),
                ('bast', models.CharField(blank=True, max_length=50, verbose_name='Bast Code')),
                ('qua_dam', models.CharField(blank=True, max_length=50, verbose_name='Qua Dam Code')),
                ('legacy_code', models.CharField(blank=True, max_length=50, verbose_name='Legacy Code')),
                ('work_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contractor'), ('IN', 'Intern')], default='FT', max_length=2, verbose_name='Work Type')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary or contract amount', max_digits=10, null=True, verbose_name='Salary')),
                ('duty_days', models.PositiveSmallIntegerField(default=0, help_text='Working days per month', verbose_name='Duty Days')),
                ('is_archive', models.BooleanField(default=False, help_text='Mark if no longer active', verbose_name='Archived')),
                ('archive_date', models.DateField(blank=True, help_text='When this employee was archived', null=True, verbose_name='Archive Date')),
                ('extra_info', models.TextField(blank=True, help_text='Free-form notes', verbose_name='Additional Info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_docs/%Y/%m/%d/', verbose_name='Document')),
                ('description', models.CharField(blank=True, help_text='Optional note about this file', max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Shift Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.shift', verbose_name='Assigned Shift'),
        ),
    ]
