# Generated by Django 5.2 on 2025-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Custom ID to print on badges/cards', max_length=50, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
