# Generated by Django 5.2 on 2025-04-25 08:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='4-digit calendar year this schedule applies to', validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(9999)], verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(help_text='Month of year (1–12) that this schedule applies to', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], verbose_name='Day of Week')),
                ('in_start_time', models.TimeField(verbose_name='Clock-in Start')),
                ('in_end_time', models.TimeField(verbose_name='Clock-in End')),
                ('out_start_time', models.TimeField(verbose_name='Clock-out Start')),
                ('out_end_time', models.TimeField(verbose_name='Clock-out End')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this schedule without deleting it', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employee.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Shift Schedule',
                'verbose_name_plural': 'Shift Schedules',
                'ordering': ['year', 'month', 'day_of_week', 'in_start_time'],
                'unique_together': {('shift', 'year', 'month', 'day_of_week')},
            },
        ),
    ]
