# Generated by Django 5.2 on 2025-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_shiftschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedule',
            name='in_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Clock-in End'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='in_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Clock-in Start'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='out_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Clock-out End'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='out_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Clock-out Start'),
        ),
    ]
