# Generated by Django 5.2 on 2025-04-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_shiftschedule_in_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_head_of_dep',
            field=models.BooleanField(default=False, help_text='if ture is head of department', verbose_name='Head of Department'),
        ),
    ]
