# Generated by Django 5.2 on 2025-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_is_head_of_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Employee’s full mailing address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_head_of_dep',
            field=models.BooleanField(default=False, help_text='If true, this user is the head of their department', verbose_name='Head of Department'),
        ),
    ]
