# Generated by Django 5.2 on 2025-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_address_alter_employee_is_head_of_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contract Date'),
        ),
    ]
