# Generated by Django 5.2 on 2025-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education_degree',
            field=models.CharField(blank=True, max_length=50, verbose_name='Education Degree'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='National ID'),
        ),
    ]
