# Generated by Django 5.2 on 2025-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_education_degree_employee_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Custom ID to print on badges/cards', max_digits=15, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
