# Generated by Django 5.2 on 2025-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='archive_reason',
            field=models.TextField(blank=True, help_text='Reason for archiving this employee', verbose_name='Archive Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this employee without deleting them', verbose_name='Active'),
        ),
    ]
