# Generated by Django 5.2 on 2025-05-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_archive_reason_employee_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': (), 'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': (), 'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'default_permissions': (), 'ordering': ['-uploaded_at'], 'verbose_name': 'Employee Document', 'verbose_name_plural': 'Employee Documents'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'default_permissions': (), 'ordering': ['name'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='shiftschedule',
            options={'default_permissions': (), 'ordering': ['year', 'month', 'day_of_week', 'in_start_time'], 'verbose_name': 'Shift Schedule', 'verbose_name_plural': 'Shift Schedules'},
        ),
    ]
