# Generated by Django 5.2 on 2025-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_device_admin',
            field=models.BooleanField(default=False, help_text='If true, this user is the admin of biometric devices', verbose_name='Device Administrator'),
        ),
    ]
