# Generated by Django 5.2 on 2025-05-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_is_device_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'default_permissions': (), 'ordering': ['id'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
    ]
