# Generated by Django 5.2 on 2025-04-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Your internal device code, e.g. "DEV123"', max_length=50, unique=True, verbose_name='Device ID')),
                ('name', models.CharField(help_text='E.g. "Front Gate Scanner"', max_length=150, verbose_name='Device Name')),
                ('ip_address', models.GenericIPAddressField(help_text='IPv4 or IPv6 address of the device', unpack_ipv4=True, verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(default=4370, help_text='Typically 4370 for ZKTeco devices', verbose_name='Port')),
                ('com_key', models.PositiveIntegerField(default=0, help_text='Device communication key (numeric)', verbose_name='Communication Key')),
                ('device_type', models.CharField(choices=[('AT', 'Attendance'), ('RG', 'Registration')], default='AT', max_length=2, verbose_name='Type')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', help_text='Whether this device is active or not', max_length=8, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['identifier'], name='attendance__identif_a20296_idx'), models.Index(fields=['ip_address', 'port'], name='attendance__ip_addr_0c4980_idx')],
            },
        ),
    ]
