# Generated by Django 5.2 on 2025-04-25 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employee', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_type', models.CharField(choices=[('FP', 'Fingerprint'), ('FA', 'Face'), ('IR', 'Iris'), ('RF', 'RFID Card')], default='FP', max_length=2, verbose_name='Biometric Type')),
                ('finger_position', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Right Thumb'), (1, 'Right Index'), (2, 'Right Middle'), (3, 'Right Ring'), (4, 'Right Little'), (5, 'Left Thumb'), (6, 'Left Index'), (7, 'Left Middle'), (8, 'Left Ring'), (9, 'Left Little')], help_text='Which finger (if applicable)', null=True, verbose_name='Finger Position')),
                ('template_data', models.TextField(help_text='Raw template blob or serialized string from device', verbose_name='Template Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_records', to='attendance.device', verbose_name='Registered On Device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Biometric Record',
                'verbose_name_plural': 'Biometric Records',
                'ordering': ['employee', 'biometric_type', 'finger_position'],
                'unique_together': {('employee', 'biometric_type', 'finger_position')},
            },
        ),
    ]
