# Generated by Django 5.2 on 2025-04-25 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_biometricrecord'),
        ('employee', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='When the punch was recorded', verbose_name='Event Time')),
                ('log_type', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], default='IN', help_text='Clock-in or clock-out', max_length=3, verbose_name='Type')),
                ('verification_type', models.CharField(choices=[('FP', 'Fingerprint'), ('FA', 'Face'), ('IR', 'Iris'), ('CA', 'Card/RFID'), ('MN', 'Manual Entry')], default='FP', help_text='Which modality or manual entry was used', max_length=2, verbose_name='Verification Method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='attendance.device', verbose_name='Device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='attendance__timesta_811a1b_idx')],
            },
        ),
    ]
