# Generated by Django 5.2 on 2025-04-26 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancelog'),
        ('employee', '0004_alter_shiftschedule_in_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PT', 'Pastime Leave'), ('SC', 'Sick Leave'), ('NS', 'Maternity/Paternity Leave'), ('UR', 'Emergency Leave'), ('DS', 'Salary Deduction'), ('DY', 'Duty Assignment'), ('HJ', 'Hajj Leave'), ('GH', 'Public Holiday')], max_length=2, verbose_name='Type of Leave')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('days_requested', models.DecimalField(decimal_places=2, help_text='Number of working days taken', max_digits=5, verbose_name='Days Requested')),
                ('reason', models.TextField(blank=True, help_text='Optional justification or details', verbose_name='Reason')),
                ('attachment', models.FileField(blank=True, help_text='Supporting document (e.g. doctor’s note)', null=True, upload_to='', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocations', to='employee.employee', verbose_name='Employee')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Supervisor or HR who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Employee Vocation',
                'verbose_name_plural': 'Employee Vocations',
                'ordering': ['-start_date'],
                'unique_together': {('employee', 'type', 'start_date', 'end_date')},
            },
        ),
    ]
