# Generated by Django 5.2 on 2025-04-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employeevocation'),
        ('employee', '0004_alter_shiftschedule_in_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeevacation',
            options={'ordering': ['-start_date'], 'verbose_name': 'Employee Vacation', 'verbose_name_plural': 'Employee Vacations'},
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='employee.employee', verbose_name='Employee'),
        ),
    ]
