# Generated by Django 5.2 on 2025-04-29 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_employeevacation_options_and_more'),
        ('employee', '0005_employee_is_head_of_dep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(verbose_name='Clock In')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Clock Out')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_leaves', to='employee.employee', verbose_name='Employee')),
                ('head_of_department', models.ForeignKey(blank=True, help_text='Must be a user who is marked as head_of_dep', limit_choices_to={'employee_profile__is_head_of_dep': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Head of Department')),
            ],
            options={
                'verbose_name': 'Daily Leave',
                'verbose_name_plural': 'Daily Leaves',
                'ordering': ['-requested_at'],
            },
        ),
    ]
