# Generated by Django 5.2 on 2025-04-29 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_dailyleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyleave',
            name='clock_in',
        ),
        migrations.RemoveField(
            model_name='dailyleave',
            name='clock_out',
        ),
        migrations.AddField(
            model_name='dailyleave',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Leave'),
        ),
        migrations.AddField(
            model_name='dailyleave',
            name='leave_type',
            field=models.CharField(choices=[('CI', 'Clock-In Only'), ('CO', 'Clock-Out Only'), ('CB', 'Clock-In & Clock-Out')], default='CB', max_length=2, verbose_name='Leave Type'),
        ),
        migrations.AddField(
            model_name='dailyleave',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='dailyleave',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Must be a user marked as head_of_dep', limit_choices_to={'employee_profile__is_head_of_dep': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Head of Department'),
        ),
    ]
