# Generated by Django 5.2 on 2025-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_dailyleave_clock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Attendance log status', max_digits=3, null=True, verbose_name='Status'),
        ),
    ]
