# Generated by Django 5.2 on 2025-05-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancelog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='updated_at',
        ),
    ]
