# Generated by Django 5.2 on 2025-05-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_attendancelog_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelog',
            options={'default_permissions': (), 'ordering': ['-timestamp'], 'verbose_name': 'Attendance Log', 'verbose_name_plural': 'Attendance Logs'},
        ),
        migrations.AlterModelOptions(
            name='biometricrecord',
            options={'default_permissions': (), 'ordering': ['employee', 'biometric_type', 'finger_position'], 'verbose_name': 'Biometric Record', 'verbose_name_plural': 'Biometric Records'},
        ),
        migrations.AlterModelOptions(
            name='dailyleave',
            options={'default_permissions': (), 'ordering': ['-requested_at'], 'verbose_name': 'Daily Leave', 'verbose_name_plural': 'Daily Leaves'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'default_permissions': (), 'ordering': ['name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='employeevacation',
            options={'default_permissions': (), 'ordering': ['-start_date'], 'verbose_name': 'Employee Vacation', 'verbose_name_plural': 'Employee Vacations'},
        ),
    ]
