# Generated by Django 5.2 on 2025-05-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancelog_options_and_more'),
        ('employee', '0012_employee_is_device_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('employee', 'timestamp', 'device')},
        ),
    ]
