# Generated by Django 5.2 on 2025-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendancelog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='log_type',
            field=models.CharField(blank=True, choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], help_text='Clock-in or clock-out', max_length=3, null=True, verbose_name='Type'),
        ),
    ]
