# Generated by Django 5.2 on 2025-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_attendancelog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='verification_type',
            field=models.CharField(choices=[('FP', 'Fingerprint'), ('FA', 'Face'), ('IR', 'Iris'), ('CA', 'Card/RFID'), ('PN', 'Password/PIN'), ('MN', 'Manual Entry')], default='FP', help_text='Which modality or manual entry was used', max_length=2, verbose_name='Verification Method'),
        ),
    ]
