# Generated by Django 5.2 on 2025-05-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_attendancelog_verification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('PT', 'Pastime Leave'), ('SC', 'Sick Leave'), ('NS', 'Maternity/Paternity Leave'), ('UR', 'Emergency Leave'), ('DS', 'Salary Deduction'), ('DY', 'Duty Assignment'), ('HJ', 'Hajj Leave'), ('GH', 'Public Holiday'), ('CA', 'Considerations')], max_length=2, verbose_name='Type of Leave'),
        ),
    ]
